### PR TITLE
Hard coded sequence length incorrect

### LINKED ISSUE #86: Wire Sequences
10th wire not getting solved and remains empty when input given

### PR DESCRIPTION
**Pull request by CyanRibena**

### CODE REVIEW

File: src/js/sequences/solverSequences.ts [hunk 1]
```diff
@@ -15,7 +16,7 @@ const count = {
 export function Sequences_solve(): void {
 	resetCount();
 
-	for (let i = 1; i <= 9; i++) {
```
Comment (halojenproductions) [inline src/js/sequences/solverSequences.ts:18]: So this was meant to be 10?

**Comment by halojenproductions** [comment]
I guess it needs a test that goes right to the last wire.

File: src/js/sequences/solverSequences.ts (hunk 1 above)
Comment (CyanRibena) [reply src/js/sequences/solverSequences.ts:18]: Correct

**Review by halojenproductions — APPROVED** [review]
